title: AI Quran & Sholat Assistant
description: Islamic AI Assistant for Quran and Prayer guidance.
baseurl: "/ai-quran"
url: "https://vildaesa.github.io"
lang: "id_ID"

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-dotenv

CLIENT_ID: BAA4ZnFKdGIwbyuwcc2YB5NFc9jHSVHf80xJ0-dJ2Z-ZeKOOjz11baY7Rtm6sS3K5TTooIWrXheKPv_oUA
# Firebase
API_KEY: "<%= ENV['API_KEY'] %>"
AUTH_DOMAIN: "<%= ENV['AUTH_DOMAIN'] %>"
PROJECT_ID: "<%= ENV['PROJECT_ID'] %>"
DATABASE_URL: "<%= ENV['DATABASE_URL'] %>"
STORAGE_BUCKET: "<%= ENV['STORAGE_BUCKET'] %>"
SENDER_ID: "<%= ENV['SENDER_ID'] %>"
APP_ID: "<%= ENV['APP_ID'] %>"
TEMPLATE_LICENSE: "<%= ENV['TEMPLATE_LICENSE'] %>"

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile.lock
  - sample.env
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
