title: AI Quran & Sholat Assistant
description: Islamic AI Assistant for Quran and Prayer guidance.
baseurl: "/ai-quran"
url: ""

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
